### ISSUE TITLE
Add domains in alphanumeric order

### ISSUE THREAD

**Issue by say-yawn** [mozilla-services/shavar-list-creation#132]
# About this Issue
After merging https://github.com/mozilla-services/shavar-prod-lists/pull/110, there was an "update" to the tracking protection lists even though the content of the lists did not change. Further, investigation showed that the "update" happened due to the change in the order of the domains being added lists.

# Acceptance Criteria
- [ ] Domains are added alphanumerically to the list
- [ ] `trackingprotection_tools` is replaced with `domain_utils` package as discussed in https://github.com/mozilla/openwpm-utils/issues/15

# Side Note
As a context, this was an issue when we were moving away from having a `Disconnect` category. As seen [here](https://github.com/mozilla-services/shavar-list-creation/pull/121/files#diff-8c5c15d9cbbefc2ec320aa3f2a253290L403), the `DisconnectParser` is no longer being used and the domains in the block lists and entity lists of shavar-prod-list repo are alphabetically organized and as such the order should always be same unless there was an reordering of the domains because of the company name change, merging of companies, etc.
Applying this change will result in "update" to the lists again since the lists were not in alphanumerical order.

**Comment by boolean5** [comment]
> `trackingprotection_tools` is replaced with `domain_utils` package as discussed in mozilla/openwpm-utils#15

My understanding from https://github.com/mozilla/openwpm-utils/issues/15 is that [trackingprotection-tools](https://github.com/mozilla/trackingprotection-tools) should now use `domain_utils` instead of `openwpm_utils`. 
[shavar-list-creation](https://github.com/mozilla-services/shavar-list-creation) is [still using](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L17) the `DisconnectParser` from  `trackingprotection_tools` and it is not clear how `trackingprotection_tools` could be replaced with `domain_utils`. Please, let me know if I'm missing something.

**Comment by HarshitSohaney** [comment]
Since this was merged in, can we close this @artines1
