### ISSUE TITLE
Create versioned lists to enable testing

### ISSUE THREAD

**Issue by skim1102** [mozilla-services/shavar-list-creation#90]
After Firefox 69 some of the shavar lists which were used only in the private browsing mode will now be available on normal browsing by default. To make sure we are not hindering the users' experience while browsing we want additional lists separated based on Nightly, Beta, and Release to test the lists before pushing to Release.

# Acceptance Criteria
- [ ] Have the following lists (@englehardt): <_insert lists here_> be available as three different lists
   - Figure out naming or versioning to distinguish between Nightly, Beta, and Release
- [ ] The respective lists are being used in the proper browser
   - Change the pref so that the list for Nightly should be used in Nightly, Beta for Beta, and Release for Release...
- [ ] Nice to have (?), get the lists to auto generate PR on https://github.com/mozilla-services/shavar-prod-lists every X weeks

**Comment by groovecoder** [comment]
Thanks for filing. My initial idea is to have 3 long-running branches in the shavar-prod-lists repo ...

* `master` receives Pull Requests from Disconnect; the script uses the `master` branch to create, e.g., `base-track-master-digest256`
* `beta` receives Pull Requests from `master`; the scripts uses the `beta` branch to create, e.g., `base-track-beta-digest256`
* `production` receives Pull Requests from `beta`; the script uses the `production` branch to create, e.g., `base-track-digest256`

We can either:

* Triplicate the entire config sections for the lists that need to have `master`, `beta`, and `production` versions
* Add a new config property (e.g., `list_versions_to_publish=master,beta,production`) and update the list-creation code to check for this and create the necessary versions from the appropriate branches

**Comment by englehardt** [comment]
We'd like to allow all list updates to bake with the Firefox configuration they'll be shipping with for at least a full cycle. This isn't really possible because beta has "early" beta and "late" beta, which may differ slightly depending on what's hidden behind the `EARLY_BETA_OR_EARLIER` build flag. However, it's the best we can do with our release cycle. 

> Thanks for filing. My initial idea is to have 3 long-running branches in the shavar-prod-lists repo ...
> 
>     * `master` receives Pull Requests from Disconnect; the script uses the `master` branch to create, e.g., `base-track-master-digest256`
> 
>     * `beta` receives Pull Requests from `master`; the scripts uses the `beta` branch to create, e.g., `base-track-beta-digest256`
> 
>     * `production` receives Pull Requests from `beta`; the script uses the `production` branch to create, e.g., `base-track-digest256`

The three list option makes sense if we can consume a different list in each channel (e.g., Nightly consumes the `master` list, Beta consumes `beta`, and release consumes `production`). That way, Nightly gets the newest list changes as soon as we merge. At each merge date, we first update the `release` list the current version of the `beta` list (which has had a full cycle to bake). Then, we update the `beta` list with all of the changes that have baked for at least N weeks in Nightly (where N is the cycle length).

Unfortunately, I don't think we have a build flag that allows us to consume a different list for each channel. According to [this page](https://wiki.mozilla.org/Platform/Channel-specific_build_defines) we have `NIGHTLY_BUILD`, `MOZ_DEV_EDITION`, `RELEASE_OR_BETA`, and `EARLY_BETA_OR_EARLIER`. Despite the description on that page, the `MOZ_DEV_EDITION` flag is indeed only dev edition (normal beta does not set this).

Given this constraint, we can only really consume two lists: master (aka `prerelease`) and `release`. The master list would be consumed behind an `EARLY_BETA_OR_EARLIER` flag (i.e. within Nightly and the beginning of the beta cycle). Late beta and release would consume the default (i.e., `release`) list. That means we can't merge the list updates that have baked for at least N weeks during the "early" beta to "late" beta transition, because the current Release version of Firefox would also get the updates (which have had no bake time in that version of Firefox). Thus our only option is to wait until merge date and merge the "N weeks of bake time or greater" changes after release.

This is unfortunate because it means that Firefox Beta will go from a more complete list in early beta (`prerelease`) to a less complete list in late beta (`release`), back up to a slightly more complete list in Firefox Release (`release` with the new changes). It also means that we miss the testing period of the Beta cycle that most closely represents Release (i.e., after the `EARLY_BETA_OR_EARLIER` flag is set to false).

I see three options (in order of my preference):
1. See if we can add in a channel-specific build define for `BETA_BUILD`, and use that to consume three versions of the lists.
2. See if we can serve different versions of the same list name from with Remote Settings based on the channel or Firefox version number. That is, if Beta 70 is requesting `base-track-digest256` it receives the `beta` branch and if Release 69 is requesting `base-track-digest256` it receives the `release` branch.
3. Live with the limitations described above and simply use the `EARLY_BETA_OR_EARLIER` flag with two versions of the list (`prerelease` and `release`).

The only other option I see is to update some type of list version number manually with each new build -- for example, have Firefox 69 consume `base-track-release-69-digest256`. This seems like it will require a bunch of manual work to manage and configure each new list deployment.

> We can either:
> 
>     * Triplicate the entire config sections for the lists that need to have `master`, `beta`, and `production` versions
> 
>     * Add a new config property (e.g., `list_versions_to_publish=master,beta,production`) and update the list-creation code to check for this and create the necessary versions from the appropriate branches

I much prefer the latter. Making multiple copies of the config means we'll end up forgetting to update one of them in the future and have mismatched list configs across channels.

> Have the following lists (@englehardt): <insert lists here> be available as three different lists

Lists that need to be versioned:
* `base-track-digest256`
* `content-track-digest256`
* `ads-track-digest256`
* `analytics-track-digest256`
* `social-track-digest256`
* `base-fingerprinting-track-digest256`
* `content-fingerprinting-track-digest256`
* `base-cryptomining-track-digest256`
* `content-cryptomining-track-digest256`
* `social-tracking-protection-digest256`
* `social-tracking-protection-facebook-digest256`
* `social-tracking-protection-twitter-digest256`
* `social-tracking-protection-linkedin-digest256`
* `social-tracking-protection-youtube-digest256`

> Nice to have (?), get the lists to auto generate PR on https://github.com/mozilla-services/shavar-prod-lists every X weeks

This should be a requirement. Otherwise, we're always going to have to spend time figuring out which PRs to cherry pick out of master by looking through the merge dates and doing the math to see what has baked for the minimum bake time.

Lastly, one other property we need from this procedure is the ability to fast-track list updates. We sometimes need to remove domains from the list due to updates to their policy or due to changes in classification (i.e., moving from `Advertising` to `Content`). Since these are policy changes, we shouldn't delay the reclassification of those domains. Deleting domains from the list is unlikely to cause breakage, as is moving a domain to a stricter version of a list.

**Comment by skim1102** [comment]
Logical checks for returning versioned lists:
- If lower than version X return Y
- If no exact match truncate and check match
- If higher than existing versions return Master
- If in between return the lower one (version available 68, 70 and version provided 69 then return versioned lists for 68)
